# Nome da Actions:
name: Snake Game

# Controlador do tempo que será feita a atualização dos arquivos.
on:
  schedule:
    - cron: "0 */5 * * *" # Executa a cada 5 horas
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v2

      # Gera os arquivos do snake (svg e gif)
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: lucaslucena-la  # 👈 Coloque seu nome de usuário aqui
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push opcional para debug
      - run: git status

      # Deploy para o branch output
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
